# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plan.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nplan.proto\x12\x0c\x61gentic.plan\x1a\x0c\x63ommon.proto\"\xb9\x01\n\nPlanResult\x12\x15\n\rnext_task_ids\x18\x01 \x03(\t\x12\x38\n\x08metadata\x18\x02 \x03(\x0b\x32&.agentic.plan.PlanResult.MetadataEntry\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa8\x01\n\rPlanExecution\x12/\n\x06header\x18\x01 \x01(\x0b\x32\x1f.agentic.common.ExecutionHeader\x12(\n\x06result\x18\x02 \x01(\x0b\x32\x18.agentic.plan.PlanResult\x12\x11\n\tplan_type\x18\x03 \x01(\t\x12\x15\n\rinput_task_id\x18\x04 \x01(\t\x12\x12\n\nparameters\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANRESULT_METADATAENTRY']._loaded_options = None
  _globals['_PLANRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PLANRESULT']._serialized_start=43
  _globals['_PLANRESULT']._serialized_end=228
  _globals['_PLANRESULT_METADATAENTRY']._serialized_start=181
  _globals['_PLANRESULT_METADATAENTRY']._serialized_end=228
  _globals['_PLANEXECUTION']._serialized_start=231
  _globals['_PLANEXECUTION']._serialized_end=399
# @@protoc_insertion_point(module_scope)
