# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plan.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from . import task_pb2 as task__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nplan.proto\x12\x12io.arl.proto.model\x1a\x0c\x63ommon.proto\x1a\ntask.proto\"z\n\nPlanResult\x12>\n\x16upstream_tasks_results\x18\x01 \x03(\x0b\x32\x1e.io.arl.proto.model.TaskResult\x12\x15\n\rnext_task_ids\x18\x02 \x03(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\xad\x01\n\rPlanExecution\x12\x33\n\x06header\x18\x01 \x01(\x0b\x32#.io.arl.proto.model.ExecutionHeader\x12\x1c\n\x14parent_task_exec_ids\x18\x02 \x03(\t\x12.\n\x06result\x18\x03 \x01(\x0b\x32\x1e.io.arl.proto.model.PlanResult\x12\x19\n\x11parent_plan_names\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANRESULT']._serialized_start=60
  _globals['_PLANRESULT']._serialized_end=182
  _globals['_PLANEXECUTION']._serialized_start=185
  _globals['_PLANEXECUTION']._serialized_end=358
# @@protoc_insertion_point(module_scope)
