# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x0c\x61gentic.task\x1a\x0c\x63ommon.proto\x1a\x19google/protobuf/any.proto\"\x8e\x01\n\nTaskResult\x12+\n\x0binline_data\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x12\r\n\x03uri\x18\x02 \x01(\tH\x00\x12\x11\n\tmime_type\x18\x03 \x01(\t\x12\x12\n\nsize_bytes\x18\x04 \x01(\x04\x12\x15\n\rerror_message\x18\x05 \x01(\tB\x06\n\x04\x64\x61ta\"\x91\x01\n\rTaskExecution\x12/\n\x06header\x18\x01 \x01(\x0b\x32\x1f.agentic.common.ExecutionHeader\x12(\n\x06result\x18\x02 \x01(\x0b\x32\x18.agentic.task.TaskResult\x12\x11\n\ttask_type\x18\x03 \x01(\t\x12\x12\n\nparameters\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKRESULT']._serialized_start=70
  _globals['_TASKRESULT']._serialized_end=212
  _globals['_TASKEXECUTION']._serialized_start=215
  _globals['_TASKEXECUTION']._serialized_end=360
# @@protoc_insertion_point(module_scope)
