spring:
  application:
    name: data_plane-java
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: data-plane-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

kafka:
  topic-patterns:
    task-executions: "task-executions-.*"
    plan-executions: "plan-executions-.*"
    task-executions-dlq: "task-executions-dlq-.*"
    plan-executions-dlq: "plan-executions-dlq-.*"

logging:
  level:
    com.pcallahan.agentic: DEBUG
    org.apache.kafka: INFO
    org.springframework.kafka: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

server:
  port: 8080 