# Default guardrail policies for agentic framework
# These policies serve as examples and can be customized per tenant or deployment

# Global default policies
token_limits:
  max_tokens_per_execution: 10000
  max_tokens_per_lifetime: 100000

cost_thresholds:
  max_cost_per_execution: 1.00
  max_cost_per_lifetime: 10.00

iteration_caps:
  max_iterations_per_lifetime: 100
  max_parallel_executions: 10

execution_timeouts:
  max_execution_time_seconds: 300
  max_lifetime_duration_hours: 24

# Tenant-specific policies (optional)
tenants:
  tenant123:
    token_limits:
      max_tokens_per_execution: 5000
      max_tokens_per_lifetime: 50000
    cost_thresholds:
      max_cost_per_execution: 0.50
      max_cost_per_lifetime: 5.00
    iteration_caps:
      max_iterations_per_lifetime: 50
      max_parallel_executions: 5
    execution_timeouts:
      max_execution_time_seconds: 180
      max_lifetime_duration_hours: 12

  tenant456:
    token_limits:
      max_tokens_per_execution: 20000
      max_tokens_per_lifetime: 200000
    cost_thresholds:
      max_cost_per_execution: 2.00
      max_cost_per_lifetime: 20.00
    iteration_caps:
      max_iterations_per_lifetime: 200
      max_parallel_executions: 20
    execution_timeouts:
      max_execution_time_seconds: 600
      max_lifetime_duration_hours: 48 